const ADD_TASK = 'ADD_TASK';
const SELECT_TASK = 'SELECT_TASK';
const DELETE_TASK = 'DELETE_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const CHECK_TASK = 'CHECK_TASK';


exports.ADD_TASK = ADD_TASK;
exports.SELECT_TASK = SELECT_TASK;
exports.DELETE_TASK = DELETE_TASK;
exports.UPDATE_TASK = UPDATE_TASK;
exports.CHECK_TASK = CHECK_TASK;

